---
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
    reviewers:
      - arnested
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      timezone: Europe/Copenhagen
    reviewers:
      - arnested
